=== squal0/Netbeans-java-projects/JavaProcessXML/src/xmlfiles/employees.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/employees.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE employees SYSTEM "employees.dtd">

    <employees>
    ...
    </employees>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT employees (employee)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT employee (firstname|lastname|location)*>
<!ATTLIST employee
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT firstname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lastname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT location (#PCDATA)>

=== squal0/Netbeans-java-projects/JavaProcessXML/src/xmlfiles/employees.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "employees.dtd">
<employees>
    <employee id="111">
        <firstname>Allen</firstname>
        <lastname>Smith</lastname>
        <location>Alaska</location>
    </employee>
    
    <employee id="112">
        <firstname>John</firstname>
        <lastname>Davis</lastname>
        <location>California</location>
    </employee>
    
    <employee id="113">
        <firstname>Bob</firstname>
        <lastname>Marley</lastname>
        <location>Jamaica</location>
    </employee>
    
    <employee id="114">
        <firstname>Anna</firstname>
        <lastname>Jackson</lastname>
        <location>Seychelles</location>
    </employee>
        
    <employee id="115">
        <firstname>Michelle</firstname>
        <lastname>Sawyer</lastname>
        <location>Kansas</location>
    </employee>
    
</employees>
